# Generated by Django 6.0.2 on 2026-02-26 06:57

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subissue_unique_together_alter_subissue_issue'),
        ('tickets', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sub_issue',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='issue', chained_model_field='issue', on_delete=django.db.models.deletion.PROTECT, to='core.subissue'),
        ),
    ]
