# Generated by Django 6.0.2 on 2026-02-26 06:59

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_sub_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='issue', chained_model_field='specialty', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.staff'),
        ),
    ]
