# Generated by Django 6.0.2 on 2026-02-26 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subissue',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subissue',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issue'),
        ),
    ]
